<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_my-text</name>
   <tag></tag>
   <elementGuidId>7ee44e53-b042-4fb9-971c-1876d7b92a6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#my-text-id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='my-text-id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38c8c4a8-5cd1-4b8d-8d92-e213e321679f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70c0c410-0829-4359-866d-ced054d9da50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3e9fa4bb-596d-41d1-98d9-9cb6209043df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>my-text</value>
      <webElementGuid>cc0e8c6f-905d-4d18-98cc-30cdac748e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>my-text-id</value>
      <webElementGuid>c597d90e-64c4-482c-84d9-a05b6514af34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>myprop</name>
      <type>Main</type>
      <value>myvalue</value>
      <webElementGuid>85ced758-daad-4ca5-bdac-3938598e09f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-text-id&quot;)</value>
      <webElementGuid>86d355a5-034d-4f39-bd61-932a96d6e034</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='my-text-id']</value>
      <webElementGuid>2e43f303-b6a5-434f-b307-347d15886c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6ca61660-40e2-4d19-bd48-7abfab7dc537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'my-text' and @id = 'my-text-id']</value>
      <webElementGuid>44c515bc-a928-40ea-b891-11b151016dbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
